### ISSUE TITLE
Allow YAML lists in item script containers' "mechanisms" section

### ISSUE THREAD

**Issue by ghost** [unizenscript/Denizen-For-Bukkit#12]
As an example of what this would look like, I want this to work:
```yaml
mechanisms:
    potion_effects:
    - INSTANT_HEAL,false,false
```
in the same way that this works:
```yaml
mechanisms:
    potion_effects: li@INSTANT_HEAL,false,false
```
